#!/bin/bash
# map_s3.sh
# Variables
CURRENT_DIR="$( cd "$( dirname "${0}" )" && pwd )" # Obtener el directorio actual
PARENT_DIR="$( dirname "$CURRENT_DIR" )" # Get the parent directory of the current directory
CONFIRM_SCRIPT="$CURRENT_DIR/confirm"
S3_CREDENTIALS_FILE=".s3"
# Obtener la lista de buckets disponibles
function get_bucket() {
  echo "Mostrando la lista de buckets disponibles en la cuenta AWS..."
  buckets=($(aws s3 ls | awk '{print $3}')) # Obtener solo los nombres de los buckets y guardarlos en un arreglo

  # Mostrar los nombres de los buckets con números de opción
  for i in "${!buckets[@]}"; do
    echo "$((i+1)). ${buckets[i]}"
  done

  # Solicitar al usuario que ingrese el número del bucket a montar
  read -p "Ingrese el número del bucket a montar: " bucket_number

  # Validar la entrada del usuario
  re='^[0-9]+$'
  if ! [[ $bucket_number =~ $re ]]; then
    echo "Error: La entrada no es un número válido."
    exit 1
  fi

  # Verificar si el número seleccionado está dentro del rango válido
  if ((bucket_number < 1 || bucket_number > ${#buckets[@]})); then
    echo "Error: El número seleccionado está fuera del rango válido."
    exit 1
  fi

  # Obtener el nombre del bucket seleccionado
  S3_BUCKET=${buckets[bucket_number-1]}
  echo "El bucket seleccionado es: $S3_BUCKET"
}

# Encontrar archivo con las credenciales de acceso a AWS S3
function find_s3_credentials_file() {
  S3_PASSWD_FILE=$(find / -type f -name "${S3_CREDENTIALS_FILE}")
    if [[ -z "$S3_PASSWD_FILE" ]]; then
        echo "ERROR: No se encontró el archivo '$S3_CREDENTIALS_FILE'..."
        exit 1
    fi
  echo "La ruta a las credenciales de acceso es: $S3_PASSWD_FILE"
}
# Obtener el punto de montaje
function get_mounting_point() {
  read -p "Ingrese el punto de montaje: " MOUNTING_POINT

    # Validar si el punto de montaje es válido
    if [[ ! -z "$MOUNTING_POINT" ]]; then
      # Eliminar espacios en blanco iniciales y finales
      MOUNTING_POINT=$(echo "$MOUNTING_POINT" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

      # Reemplazar espacios en blanco internos por guiones bajos
      MOUNTING_POINT=$(echo "$MOUNTING_POINT" | tr ' ' '_')

      # Verificar si el punto de montaje existe
      if [[ -d "$MOUNTING_POINT" ]]; then
        echo "El punto de montaje '$MOUNTING_POINT' ya existe."
      else
        # Comprobar si se tienen permisos de escritura en el directorio padre
        local parent_dir=$(dirname "$MOUNTING_POINT")
        if [[ -w "$parent_dir" ]]; then
          valid_mounting_point=true
          echo "El punto de montaje ingresado es: $MOUNTING_POINT"
        else
          echo "No se tienen permisos de escritura en el directorio padre '$parent_dir'."
        fi
      fi
    else
      echo "El punto de montaje no puede estar vacío."
    fi
}

function check_mounting_path() {
  MOUNTING_PATH="/var/$MOUNTING_POINT"
    # verificar la existencia del punto de montaje
    echo "Verificando la existencia del directorio temporal..."
    if [ -d "$MOUNTING_PATH" ]; then
        echo "El punto de montaje '$MOUNTING_PATH' existe."
        sudo chmod 777 "$MOUNTING_PATH"
    else
        echo "ERROR: El punto de montaje '$MOUNTING_PATH' no existe."
        echo "Creando el punto de montaje '$MOUNTING_PATH'."
        sudo mkdir -p "$MOUNTING_PATH" 
        sudo chmod 777 "$MOUNTING_PATH"
    fi
}
function mount_bucket() {
  echo "Montando el bucket: '$S3_BUCKET' --> '$MOUNTING_PATH'"
  if sudo s3fs "$S3_BUCKET" "$MOUNTING_PATH" -o passwd_file=$S3_PASSWD_FILE -o nonempty; then
    echo "El bucket '$S3_BUCKET' fue montado en '$MOUNTING_PATH'."
  else
    echo "Error al montar el bucket '$S3_BUCKET' en '$MOUNTING_PATH'."
  fi
}
# Agregar entradas en /etc/fstab para montar las particiones al reiniciar el sistema
function edit_fstab() {
  # Agregar entradas en /etc/fstab para montar las particiones al reiniciar el sistema
  echo "Agregar entradas en /etc/fstab para montar bucket '$S3_BUCKET' al reiniciar el sistema..."
  echo "s3fs#${S3_BUCKET//\"/} ${MOUNTING_PATH//\"/} s3fs _netdev,use_cache=/tmp,nonempty,allow_other,uid=1000,gid=1000 0 2" | sudo tee -a /etc/fstab
}
# Función que monta automáticamente la partición sin reiniciar
function mount_automatically() {
    if sudo mount -a; then
        echo "Particiones montadas automáticamente con éxito"
    else
        echo "ERROR: Hubo un error al montar las particiones automáticamente"
        exit 1
    fi
}
function map_s3() {
  echo "****************MAP S3****************"
  get_bucket
  find_s3_credentials_file
  get_mounting_point
  check_mounting_path
  mount_bucket
  edit_fstab
  mount_automatically
  echo "****************ALL DONE****************"
}
map_s3
