#!/bin/bash
# mkparts.sh
# Variables
CURRENT_DIR="$( cd "$( dirname "${0}" )" && pwd )" # Obtener el directorio actual
PARENT_DIR="$( dirname "$CURRENT_DIR" )" # Get the parent directory of the current directory
CONFIRM_SCRIPT="$CURRENT_DIR/confirm"

# Obtener el punto de montaje
function get_mounting_point() {
  local valid_mounting_point=false

  while [[ "$valid_mounting_point" = false ]]; do
    read -p "Ingrese el punto de montaje: " MOUNTING_POINT

    # Validar si el punto de montaje es válido
    if [[ ! -z "$MOUNTING_POINT" ]]; then
      # Eliminar espacios en blanco iniciales y finales
      MOUNTING_POINT=$(echo "$MOUNTING_POINT" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

      # Reemplazar espacios en blanco internos por guiones bajos
      MOUNTING_POINT=$(echo "$MOUNTING_POINT" | tr ' ' '_')

      # Verificar si el punto de montaje existe
      if [[ -d "$MOUNTING_POINT" ]]; then
        echo "El punto de montaje '$MOUNTING_POINT' ya existe."
      else
        # Comprobar si se tienen permisos de escritura en el directorio padre
        local parent_dir=$(dirname "$MOUNTING_POINT")
        if [[ -w "$parent_dir" ]]; then
          valid_mounting_point=true
          echo "El punto de montaje ingresado es: $MOUNTING_POINT"
        else
          echo "No se tienen permisos de escritura en el directorio padre '$parent_dir'."
        fi
      fi
    else
      echo "El punto de montaje no puede estar vacío."
    fi
  done
}

# Obtener la unidad a particionar y el número de particiones del usuario
function get_dev() {
  unidades=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -e '^NAME' -e 'disk' | awk '{print $1, $2}')
  unidad=$(dialog --stdout --menu "Seleccione la unidad a particionar:" 10 50 0 $unidades)
  # Validar la unidad ingresada
  if ! [ -b "/dev/$unidad" ]; then
    echo "La unidad especificada no existe."
    exit 1
  fi

  # Comprobar si la unidad ha sido montada previamente
  if lsblk -o MOUNTPOINT | grep -q "^/dev/$unidad"; then
    echo "La unidad seleccionada ya está montada. No se puede particionar."
    exit 1
  fi

}

function confirm() {
  num_particiones=$contador
  # Mostrar la información ingresada y solicitar confirmación al usuario
  dialog --yesno "Se crearán '$num_particiones' particiones, una para cada dominio en la unidad: '/dev/$unidad'. ¿Desea proceder?" 10 50
  response=$?
  if [ $response -eq 0 ]; then
    echo "El usuario confirmó la ejecución."
    # Coloca aquí las acciones a realizar si el usuario confirma
    format_parts
    check_mountung_path
    iteration
    edit_fstab
  else  
    echo "El usuario canceló la ejecución."
    # Coloca aquí las acciones a realizar si el usuario cancela
    exit 1
  fi
}

# Formatear las particiones con el formato especificado por el usuario
function format_parts() {
  echo "Procediendo a formatear las particiones creadas."
  formato="ext4"
  sudo mkfs.$formato "/dev/${unidad}"
  echo "Las particiones creadas fueron formateadas exitosamente."
  echo "Filtrando la unidad de disco xvdf:"
  lsblk --paths | grep $unidad
}
function check_mountung_path() {
  MOUNTING_PATH="/var/$MOUNTING_POINT"
    # verificar la existencia del punto de montaje
    echo "Verificando la existencia del directorio temporal..."
    if [ -d "$MOUNTING_PATH" ]; then
        echo "El punto de montaje '$MOUNTING_PATH' existe."
    else
        echo "ERROR: El punto de montaje '$MOUNTING_PATH' no existe."
        echo "Creando el punto de montaje '$MOUNTING_PATH'."
        sudo mkdir -p "$MOUNTING_PATH" 
        sudo chmod 777 "$MOUNTING_PATH"
    fi
}
function iteration() {
  # Obtenemos la partición correspondiente
  particion="/dev/${unidad}"
  
  # Montar la partición
  echo "Montando la partición: '$particion' --> '$MOUNTING_PATH'"
  if sudo mount "$particion" "$MOUNTING_PATH"; then
    echo "Partición '$particion' fue montada en '$MOUNTING_PATH'."
  else
    echo "Error al montar la partición '$particion' en '$MOUNTING_PATH'."
    echo "Asegúrese de que la partición exista y el punto de montaje esté disponible."
    echo "Revise los permisos y la configuración del sistema."
  fi
  lsblk --paths | grep $unidad
}

# Agregar entradas en /etc/fstab para montar las particiones al reiniciar el sistema
function edit_fstab() {
  # Agregar entradas en /etc/fstab para montar las particiones al reiniciar el sistema
  echo "Agregar entradas en /etc/fstab para montar la particion '$particion' al reiniciar el sistema..."
  echo "${particion//\"/} ${MOUNTING_PATH//\"/} ${formato//\"/} defaults 0 0" | sudo tee -a /etc/fstab
}

function nextcloud_partitions() {
  echo "****************MKPARTS****************"
  get_mounting_point
  get_dev
  confirm
  echo "****************ALL DONE****************"
}
nextcloud_partitions
