#!/bin/bash
# sysview.sh
# Función para obtener información de uso de CPU
function get_cpu_usage {
    cpu_info=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
    if [[ -n "${cpu_info}" ]]; then
        cpu_usage="${cpu_info}%"
        echo "${cpu_usage}"
    else
        echo "Error al obtener el uso de CPU"
        exit 1
    fi
}
# Función para obtener información de uso de memoria
function get_mem_usage {
    mem_info=$(free -m | grep "Mem" | awk '{print $3 "/" $2 " MB"}')
    if [[ -n "${mem_info}" ]]; then
        mem_usage="${mem_info}"
        echo "${mem_usage}"
    else
        echo "Error al obtener el uso de memoria"
        exit 1
    fi
}
# Función para obtener información de uso de espacio en disco
function get_disk_usage {
    disk_info=$(df -h / | grep -Eo '[0-9]+%')
    if [[ -n "${disk_info}" ]]; then
        disk_usage="${disk_info}"
        echo "${disk_usage}"
    else
        echo "Error al obtener el uso de espacio en disco"
        exit 1
    fi
}
# Función para imprimir información de monitoreo
function print_monitoring_info {
    cpu_usage=$(get_cpu_usage)
    mem_usage=$(get_mem_usage)
    disk_usage=$(get_disk_usage)

    if [[ -n "${cpu_usage}" && -n "${mem_usage}" && -n "${disk_usage}" ]]; then
        echo "Uso de CPU: ${cpu_usage}"
        echo "Uso de memoria: ${mem_usage}"
        echo "Uso de espacio en disco: ${disk_usage}"
    else
        echo "Error al imprimir información de monitoreo"
        exit 1
    fi
}
print_monitoring_info
