#!/bin/bash
# sysview.sh
# Función para obtener información de uso de CPU
function get_cpu_usage {
    cpu_info=$(top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}')
    cpu_usage="${cpu_info}%"
    echo "${cpu_usage}"
}
# Función para obtener información de uso de memoria
function get_mem_usage {
    mem_info=$(free -m | grep "Mem" | awk '{print $3 "/" $2 " MB"}')
    mem_usage="${mem_info}"
    echo "${mem_usage}"
}
# Función para obtener información de uso de espacio en disco
function get_disk_usage {
    disk_info=$(df -h / | grep -Eo '[0-9]+%')
    disk_usage="${disk_info}"
    echo "${disk_usage}"
}
# Función para imprimir información de monitoreo
function print_monitoring_info {
    cpu_usage=$(get_cpu_usage)
    mem_usage=$(get_mem_usage)
    disk_usage=$(get_disk_usage)
    echo "Uso de CPU: ${cpu_usage}"
    echo "Uso de memoria: ${mem_usage}"
    echo "Uso de espacio en disco: ${disk_usage}"
}
print_monitoring_info
